### ISSUE TITLE
Credly badges

### ISSUE THREAD

**Issue by ragamouf** [au-research/ARDC-23-things#10]
Taking on @tom-h's suggestion to split content from reward structures, it would be expedient in the first instance to delete all credly guff, and insert this when a new credly account and 23 badge redesigns are available.
Can we make this decision in the scope of this project?

**Comment by ragamouf** [comment]
I just had a chat with Natasha about credly badges and we resolved that perhaps we only need 1 credly badge for the whole 23 things. This is more manageable for comms and a new credly account. 
This would require changing our checklist to delete credly guff, rather than include it.

**Comment by mpfl** [comment]
I had a further chat with Natasha about this.

IMO we are not running a training course and do not have any way of policing the badges or certificates. All we are doing - at this time - is providing a set of training materials that others can use for themselves. It's up to them to provide certification.

**Comment by rowan-ardc** [comment]
Remove all credly text & links or retain?

**Comment by mpfl** [comment]
Would be helpful if I actually provided the guidance that I meant to...

Please remove all references to credly. They can be put back in at a later date if there is both demand and capacity.

**Comment by tom-h** [comment]
~~See Pull Request https://github.com/au-research/ARDC-23-things/pull/47~~

~~If we use the get-help.md template then we can easily update the help/reward text, including adding or removing the credly badges.~~

See PR #48 ... help text is removed from the core text altogether, and placed in the layout
