### ISSUE TITLE
Broken link - Thing 1 

### ISSUE THREAD

**Issue by areff2000** [au-research/ARDC-23-things#101]
From contact@ardc: 20.10.22

I hope this message finds you well. I've just come across your great resource 'All the Research Data things', and was reading through Thing 1.

I just wanted to let you know that the link in [Thing 1](https://au-research.github.io/ARDC-23-things/researchdata/thing-01) related to defining data from the University of Oregon is a stale link, the information can still be found at this link: https://guides.library.oregonstate.edu/research-data-services/data-management-define-data

I hope this was helpful, and thanks for the amazing resource.

Best,
ky, WEHI 
Data Modeler 
Research Data Governance and Management

**Comment by tom-h** [comment]
thanks @areff2000 you can let them know that the link is updated per their suggestion.
