### ISSUE TITLE
Need replacement content: Thing 15, DMPs

### ISSUE THREAD

**Issue by NicholaBurton** [au-research/ARDC-23-things#14]
Within Thing-15: Learn More (Templates for DMPs), there is a substantial piece of content that is missing and requires replacement. 

The missing content is: 
"Check out how The University of Queensland is re-imagining DMPs in the blog post DMRs, making DMP’s relevant again"
(http://andscentral.blogspot.com.au/2017/05/dmrs-making-dmps-relevant-again.html)

Does anyone have a suggestion for replacement content?

**Comment by mpfl** [comment]
How about this extended abstract from eResearch Australasia 2017?

https://conference.eresearch.edu.au/2017/08/piloting-the-research-data-manager-system-at-uq-dmrs-pids-and-tears-of-joy/

**Comment by NicholaBurton** [comment]
Aha, I just found the original blog post on the wayback machine!

https://web.archive.org/web/20180509004414/http://andscentral.blogspot.com.au/2017/05/dmrs-making-dmps-relevant-again.html

a) I don't think the abstract really communicates the blog's message about DMPs as living documents, even though it is about the same project
b) is it a bad idea to just link through to web.archive.org?

**Comment by mpfl** [comment]
I don't think linking to web.archive.org is necessarily a bad thing. What do you think, @ragamouf?

**Comment by NicholaBurton** [comment]
Given that @ragamouf has just headed off on a month of leave, I'm going to go with the web.archive.org link and Liz can object later if needed!

**Comment by mpfl** [comment]
http://ardccentral.blogspot.com/2017/05/dmrs-making-dmps-relevant-again.html

**Comment by NicholaBurton** [comment]
@ragamouf suggested an alternative blog article by Sarah Jones - what's the link for that one?

**Comment by ragamouf** [comment]
the blog post: http://www.dcc.ac.uk/blog/dmp-inspiration-down-under 
the ARDC webinar video: https://ardc.edu.au/resource/data-management-planning-lessons-for-europe-webinar-video/
