### ISSUE TITLE
Thing 5: Data sharing

### ISSUE THREAD

**Issue by tom-h** [au-research/ARDC-23-things#18]
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replaced outdated standard text (sharing)
- [x]  Remove outdated standard text (credly)

cf PR #27 

- [x]  Check GDrive for updated content
- [x]  Fix problematic content

**Comment by rowan-ardc** [comment]
Checked G drive.  [Google doc for this thing](https://docs.google.com/document/d/1LYOEGW633yXMZhJuf3R2LrZBG4yia7RQkS4xOKEzk4c/edit#) contains many minor edits and some sections of substitute text.

**Comment by klevetate** [comment]
Thanks @rowan-ardc - i'll incorporate those changes from g.doc

**Comment by mpfl** [comment]
I have incorporated the changes from the gdoc. Closing issue.
