### ISSUE TITLE
Thing 6: curation & preservation

### ISSUE THREAD

**Issue by tom-h** [au-research/ARDC-23-things#19]
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replaced outdated standard text (sharing)
- [x]  Remove outdated standard text (credly)

cf PR #28 

- [x]  Check GDrive for updated content
- [x]  Fix problematic content

**Comment by rowan-ardc** [comment]
Checked G drive

**Comment by edwardshaddow** [comment]
ANDS link to data preservation in step 2 of Getting Started. Couldn't find ARDC equivalent.

**Comment by tom-h** [comment]
Hmm, yes. Maybe point to the Digital preservation coalition https://www.dpconline.org/ ? Aus preserves?

**Comment by edwardshaddow** [comment]
Have added a link to the DPC handbook as step 3 in Getting Started.
