### ISSUE TITLE
Thing 1: Getting started with research data

### ISSUE THREAD

**Issue by mpfl** [au-research/ARDC-23-things#2]
- [x]  Check GDrive for updated content
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replaced outdated standard text (sharing)
- [x]  Remove outdated standard text (credly)
- [x]  Fix problematic content

**Comment by rowan-ardc** [comment]
Checked G drive

**Comment by edwardshaddow** [comment]
Dead link in the 'Defining Research Data from the University of Oregon library' page. Archiving & Preservation should go to https://researchguides.uoregon.edu/data-management/archiving. Contact them to update or find alternative?
