### ISSUE TITLE
Thing 7: Data citation for access & attribution

### ISSUE THREAD

**Issue by NicholaBurton** [au-research/ARDC-23-things#21]
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replace outdated standard text
- [x]  Remove references to Credly
- [x]  Check GDrive for updated content
- [x]  Fix problematic content

**Comment by edwardshaddow** [comment]
Thing refers to ANDS resource https://www.ands.org.au/working-with-data/publishing-and-reusing-data/licensing-for-reuse.

Closest ARDC resource I can find is the research data rights management guide, but this should be referenced in the 'learn more' section.
