### ISSUE TITLE
Thing 10: Sharing sensitive data

### ISSUE THREAD

**Issue by NicholaBurton** [au-research/ARDC-23-things#25]
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replace outdated standard text
- [x]  Remove references to Credly
- [x]  Check GDrive for updated content
- [x]  Fix problematic content

**Comment by NicholaBurton** [comment]
To resolve: 
Currently, linked-to RDA record https://researchdata.ands.org.au/de-identified-dataset-reproductive-outcome/617280/ has broken link to dataset. Dataset can now be found at https://data.unisa.edu.au/dap/dataset.aspx?datasetid=96137. Resolve with RDA team?

**Comment by NicholaBurton** [comment]
For now will link directly to data.unisa.edu.au

**Comment by edwardshaddow** [comment]
Thing has several references to ANDS resources that don't seem to be replicated on ARDC site. Closest I could find was https://ardc.edu.au/resources/working-with-data/de-identification/ but the page actually links to several ANDS resources.

This might be a non-issue, but flagging anyway.
