### ISSUE TITLE
Thing 2: Issues in research data management

### ISSUE THREAD

**Issue by ragamouf** [au-research/ARDC-23-things#3]
- [x] Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replaced outdated standard text (sharing/credly)

cf PR #50 

- [x]  Fix problematic content
- [x] update from gdrive updates

**Comment by ragamouf** [comment]
https://docs.google.com/document/d/1wuNdccfadlXEzqSmgEjndoQrBohua8dTilJxp_dZccs/edit see previous content edit here

**Comment by tom-h** [comment]
I think the thing 2 edits are here: https://docs.google.com/document/d/1Nxab5TTlkt_dbbEVwHRvd19GQ3fK78OpkkbsVlWxNxU/edit

**Comment by tom-h** [comment]
I think this may already reflect the changes made on the gdrive as well, but it will need to be double-checked.

**Comment by ragamouf** [comment]
ok I'll double check it, then close this issue.

**Comment by ragamouf** [comment]
woop di woo! Thing 2 is good to go. (Pending final assessment by Style Guide Counsel).

**Comment by edwardshaddow** [comment]
Thing 2 has a link to an ANDS/ARDC resource, style guide suggest having an alternative alongside it - https://www.ands.org.au/working-with-data/publishing-and-reusing-data/data-provenance
