### ISSUE TITLE
Thing 13: Walk the crosswalk

### ISSUE THREAD

**Issue by tom-h** [au-research/ARDC-23-things#33]
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replaced outdated standard text (sharing)
- [x]  Remove outdated standard text (credly)

cf PR https://github.com/au-research/ARDC-23-things/pull/40

- [x]  Check GDrive for updated content
- [x]  Fix problematic content

**Comment by rowan-ardc** [comment]
Checked G drive
