### ISSUE TITLE
Thing 19:  APIs & Apps

### ISSUE THREAD

**Issue by tom-h** [au-research/ARDC-23-things#35]
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replaced outdated standard text (sharing)
- [x]  Remove outdated standard text (credly)

cf PR #42 

- [x]  Check GDrive for updated content
- [ ]  Fix problematic content

**Comment by rowan-ardc** [comment]
Checked G drive

**Comment by edwardshaddow** [comment]
Codeacademy no longer do the API track, how is this for an alternative? https://www.freecodecamp.org/news/apis-for-beginners-full-course/

**Comment by edwardshaddow** [comment]
Can someone please login and check the following links actually resolve to where they are meant to.

OAI-PMH Provider: https://documentation.ands.org.au/login.action?os_destination=%2Fservices%2Fcollections-registry-api%2Foai%2Findex.action

Research Activity Grants API: https://documentation.ands.org.au/login.action?os_destination=%2Fservices%2Fresearch-activity-api%2Findex.action

**Comment by rowan-ardc** [comment]
Here is a public link for the OAI-PMH provider
https://documentation.ands.org.au/display/DOC/OAI-PMH+Provider
and one for the api
https://documentation.ands.org.au/display/DOC/Research+Activities+API

**Comment by tom-h** [comment]
Not sure about the API course, but a 30 second glance and it looks okay to me. We also delivered an introduction to APIs webinar a couple of years back that might suffice. https://www.youtube.com/watch?v=Da57ctFHRS4 ...but I bet the freecodecamp one is slicker.

**Comment by edwardshaddow** [comment]
> Here is a public link for the OAI-PMH provider
> https://documentation.ands.org.au/display/DOC/OAI-PMH+Provider
> and one for the api
> https://documentation.ands.org.au/display/DOC/Research+Activities+API

Perfect, thank you! Have updated my branch for this thing.

**Comment by edwardshaddow** [comment]
> Not sure about the API course, but a 30 second glance and it looks okay to me. We also delivered an introduction to APIs webinar a couple of years back that might suffice. https://www.youtube.com/watch?v=Da57ctFHRS4 ...but I bet the freecodecamp one is slicker.

I added the freeCodeCamp link as it is very hands on and has really good docs that go along with it. That said, feel free to swap with the ARDC one if you want as it is a 2 hour long tutorial.
