### ISSUE TITLE
Thing 20: Do/Find it with data

### ISSUE THREAD

**Issue by tom-h** [au-research/ARDC-23-things#36]
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replaced outdated standard text (sharing)
- [x]  Remove outdated standard text (credly)

cf PR #43 

- [x]  Check GDrive for updated content
- [x]  Fix problematic content

**Comment by rowan-ardc** [comment]
Checked G drive

**Comment by edwardshaddow** [comment]
Google Fusion Tables and the Fusion Tables API have been discontinued.

Alternatives are BigQuery, Cloud SQL, Maps Platform, and Data Studio.

Option to remove this section from the thing, or replace it with one of the above. I'm not sure what people are actually using/what would be helpful.

**Comment by mpfl** [comment]
Removed Google Fusion Tables exercise.
