### ISSUE TITLE
Thing 21: Tools of the trade

### ISSUE THREAD

**Issue by tom-h** [au-research/ARDC-23-things#37]
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replaced outdated standard text (sharing)
- [x]  Remove outdated standard text (credly)

cf PR #44 

- [x]  Check GDrive for updated content
- [x]  Fix problematic content

**Comment by rowan-ardc** [comment]
Checked G drive.  @ragamouf has identified content to be changed and provided substitute text in the [google document for this thing](https://docs.google.com/document/d/12rDNKPNh_AGtf6_edpm8MwxPAaN8BrBKnOKJWMDLnhw/edit).

**Comment by tom-h** [comment]
Everything is updated for this thing in my [branch](https://github.com/tom-h/ARDC-23-things/blob/edit-thing-21/_things/thing-21.md), except for (1) under getting started. We need a new example article. @ragamouf has suggested [this paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3333423), but I think it would be better to find a published one.

**Comment by mpfl** [comment]
Thankfully the paper has been published since this issue was last touched.
