### ISSUE TITLE
Thing 22: what's in a name

### ISSUE THREAD

**Issue by tom-h** [au-research/ARDC-23-things#38]
- [x]  Copy to "things" directory
- [x]  Clean up formatting
- [x]  Replaced outdated standard text (sharing)
- [x]  Remove outdated standard text (credly)

cf PR #45 

- [x]  Check GDrive for updated content
- [x]  Fix problematic content

**Comment by tom-h** [comment]
There's a lot of problematic content in this one... e.g., VLs are now ARDC not Nectar

**Comment by rowan-ardc** [comment]
Checked G drive

**Comment by edwardshaddow** [comment]
Link to missing (possibly Nectar) YouTube playlist. Matthias is following up with comms.

**Comment by mpfl** [comment]
Old Nectar website is still the source of truth for a lot of this information. Closing issue for now until ARDC comms have had the opportunity to review that content.
