### ISSUE TITLE
Thing 11: Metadata

### ISSUE THREAD

**Issue by klevetate** [au-research/ARDC-23-things#4]
- [x] Copy to "things" directory
- [x] Clean up formatting
- [x] Replaced outdated standard text (sharing/credly)

cf PR #49 

- [x] check GDrive for updates
- [x] Fix problematic content

**Comment by tom-h** [comment]
This thing has a custom "get-help / interaction" blurb, which I have removed for now:

---

### Well Done! You are halfway through\
- Now take some time to reflect

Go back over any notes that you may have made as you went through the
Things

Consider:

-   Why you are doing 23things - are you achieving this?
-   Let us know on the [Data Librarians Google+
    page](https://plus.google.com/u/0/communities/105455769899183786145 "Data Librarians Google+ page")
    if you are achieving your desired outcomes, have discovered new
    things you didn't think you would, found that data is your "thing",
    or just reflect on your journey so far

----

**Comment by klevetate** [comment]
Done! @tom-h do I close this issue now? Or leave it open until Matthias merges my pull request?

**Comment by tom-h** [comment]
Once the PR (#52) is merged, you can close the issue. For that to happen, first merge the PR in your own fork where I resolve conflicts and bring your fork up to date, then @mpfl or I can merge your PR with changes to thing 11 and 13.

**Comment by tom-h** [comment]
You might just want to double check the file before closing this issue

**Comment by klevetate** [comment]
File checked
