### ISSUE TITLE
Thing 14: Identifiers and linked data

### ISSUE THREAD

**Issue by NicholaBurton** [au-research/ARDC-23-things#6]

**Comment by NicholaBurton** [comment]
This Thing was already claimed, closing to avoid conflict!

**Comment by edwardshaddow** [comment]
Looks like http://www.linkeddatatools.com is down (checked on down for everyone)? The entire 'Challenge Me' section relies on this site.

**Comment by NicholaBurton** [comment]
Down for me as well! Unsurprisingly. I'll have a look into the history of the site and see if the resources have been migrated somewhere...

**Comment by NicholaBurton** [comment]
Looks like it's gone-gone. Still available via the wayback machine, but I wonder if we should just find some replacement content. I'll re-open the other issue for this Thing (this is the one that I opened at the same time as Rowan opened his and then had to close again) and note the problem.
