### ISSUE TITLE
Thing 14: Identifiers and linked data

### ISSUE THREAD

**Issue by rowan-ardc** [au-research/ARDC-23-things#7]
- [x] Copy to things directory
- [x] Clean up formatting
- [x]  Replaced outdated standard text (sharing)
- [x]  Remove outdated standard text (credly)
- [x]  Check GDrive for updated content
- [x]  Fix problematic content
- [x] Check the thing against the style guide

**Comment by rowan-ardc** [comment]
Complete against checklist as of 11/02/2020

**Comment by NicholaBurton** [comment]
@edwardshaddow noted that http://www.linkeddatatools.com is down - poking around on the [Wayback Machine](https://web.archive.org/web/20190831043934/http://www.linkeddatatools.com/introducing-rdf) it looks like it was still around last year, so must be pretty recent.

The entire Challenge Me section relies upon this content, so we will need a replacement. I'm not sure if we need another source for the same information, or if things have moved on... Who's the subject matter expert for this?

**Comment by mpfl** [comment]
http://www.linkeddatatools.com/ is back up! Closing this issue.
